version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.29.78:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


# docker-compose up -d

# docker exec kafka kafka-topics --list --bootstrap-server 192.168.29.78:9092


# docker ps
